 var spotObj = 
    [
        mornPier = 
        {
            name:" Mornington Pier",
            maxWindKm: 35,
            sheltFrom: ['S','ESE','SE'],
            goodWind: ['S','ESE','SE','E','ENE', 'WSW', 'SW'],
            tideException: ['none'],
            chnceFish: 6,
            goodFish: 3,
            species: ['Snapper', 'Squid', 'Garfish', 'Australian Salmon', 'King George Whiting', 'Flathead', 'Leatherjacket', 'Kingfish'],
            matchedSpecies: [],
            tips: ['Snapper/Kingfish: Best fished with a running sinker rig and whole fresh calamari, silver whiting or garfish', 'The high tide on sun up is most productive, as fish will often feed close in the shallows. Your cast needs to be about 20m. Or 70m as that is the edge of the reef system.'],
            isSheltered: '<img id="outputIcon" src="img/cross.png">',
            distanceFrom: 1,
            toilets: '<img id="outputIcon" src="img/tick.png">',
            image: '<img id="spotImg" src="img/morn.jpg">',
            desc: "Mornington Pier was first built in the 1850s, providing a safe berth for steamships carrying holiday makers from Melbourne. It was was also a busy departure point for vessels carrying produce to the Melbourne markets before rail arrived in the early 1890s.<br/><br/>"+
                "Today the pier is a popular destination for a range of recreational activities including sightseeing, fishing and scuba diving.",
            takeMe: "https://www.google.com.au/maps/place/2+Schnapper+Point+Dr,+Mornington+VIC+3931/@-38.212902,145.0309502,17z/data=!3m1!4b1!4m5!3m4!1s0x6ad5d946b41d33d9:0x396b4071d917bab6!8m2!3d-38.212902!4d145.0331389?q=2+Schnapper+Point+Drive,+Mornington+VIC+3931&rlz=1C1NHXL_enAU692AU692&um=1&ie=UTF-8&sa=X&ved=0ahUKEwiX5rPL8PXPAhWDkpQKHX9_AE0Q_AUICCgB",
            coords: [-38.212170, 145.033879],
            spotID: 13856,
            pts:2
        },
        mtMartha = 
        {
            name:" Mt Martha Rocks",
            maxWindKm: 35,
            sheltFrom: ['ESE','SE'],
            goodWind: ['S','ESE','SE','E','ENE', 'WSW', 'SW'],
            tideException: ['none'],
            chnceFish: 4,
            goodFish: 3,
            species: ['Snapper', 'Squid', 'King George Whiting', 'Australian Salmon', 'Garfish', 'Flathead', 'Kingfish'],
            matchedSpecies: [],
            tips: ['Safety first when rock fishing - no running, be sure-footed, never turn your back on the water, DO NOT FISH ALONE specially if you are not familiar with the area.', ' For best results when targeting large Snapper head down during an onshore blow during dawn or dusk. Garfish in large numbers can often be caught when making use of a good berley mix to attract the large schools.', 'For Snapper use whole fish baits such as pilchard and silver whiting (often squid will also work). Squid can be caught with artificial and baited jigs and Garfish are best fished for using silver fish or thin fillets of pilchard under a floating jig.'],
            isSheltered: '<img id="outputIcon" src="img/cross.png">',
            distanceFrom: 35,
            toilets: '<img id="outputIcon" src="img/cross.png">',
            image: '<img id="spotImg" src="img/mm.jpg">',
            desc: "A three kilometre stretch of rocky platforms along the coastline of Port Phillip Bay. The Mount Martha Cliffs offer year round species to the keen angler who is willing to take the long track down the often steep cliffs.",
            takeMe:"https://www.google.com.au/maps/dir//361+Esplanade,+Mount+Martha+VIC+3934/@-38.2819094,144.9607032,13755m/data=!3m2!1e3!4b1!4m9!4m8!1m0!1m5!1m1!1s0x6ad5dacdfbb2f595:0xa51f42eecae342b1!2m2!1d144.9957226! 2d-38.2819146!3e0",
            coords: [-38.281999, 144.995531],
            spotID: 13856,
            pts:2
        },
        dromPier = 
        {
            name:" Dromana Pier",
            maxWindKm: 35,
            sheltFrom: ['ESE','S'],
            goodWind: ['S','ESE','SE','WSW', 'SW'],
            tideException: ['none'],
            chnceFish: 2,
            goodFish: 0,
            species: ['Flathead', 'Australian Salmon', 'Garfish', 'Snapper'],
            matchedSpecies: [],
            tips: ['Use a rod', 'Perhaps a rod and reel would be nice'],
            isSheltered: '<img id="outputIcon" src="img/cross.png">',
            distanceFrom: 1,
            toilets: '<img id="outputIcon" src="img/tick.png">',
            image: '<img id="spotImg" src="img/dr.jpg">',
            desc: "What it lacks for in size it makes up for in quality.  This little pier at the heart of the Dromana township, is an absolute staple for the late afternoon gar crowd.",
            takeMe: "https://www.google.com.au/maps/place/38%C2%B008'47.7%22S+145%C2%B006'58.0%22E/@-38.3318651,144.9626081,508m/data=!3m1!1e3!4m5!3m4!1s0x0:0x0!8m2!3d-38.146594!4d145.116101",
            coords: [-38.332074, 144.965034],
            spotID: 13856,
            pts:0
        },
        rosePier = 
        {
            name:" Rosebud Pier",
            maxWindKm: 35,
            sheltFrom: ['ESE','S'],
            goodWind: ['S','ESE','SE','WSW', 'SW'],
            tideException: ['none'],
            chnceFish: 2,
            goodFish: 0,
            species: ['Flathead', 'Australian Salmon', 'Garfish', 'Squid'],
            matchedSpecies: [],
            tips: ['Rosebud tends to produce small squid, and small salmon when there is a northerly blowing.'],
            isSheltered: '<img id="outputIcon" src="img/cross.png">',
            distanceFrom: 1,
            toilets: '<img id="outputIcon" src="img/tick.png">',
            image: '<img id="spotImg" src="img/rb.jpg">',
            desc: "In the early days Rosebud suffered from a lack of direct access to Melbourne. When a pier was finally built in 1888, it failed to extend into the deep water, so ferries and passenger ships from the metropolis had to dock at Dromana. Although some companies offered ferry passengers a ride to Rosebud after they disembarked at Dromana, the bulk of the tourism trade went to Dromana and nearby Arthurs Seat, and Dromana remained the transportation hub for goods brought by road and sea.",
            takeMe:"https://www.google.com.au/maps/place/38%C2%B008'47.7%22S+145%C2%B006'58.0%22E/@-38.3527283,144.9061628,508m/data=!3m1!1e3!4m5!3m4!1s0x0:0x0!8m2!3d-38.146594!4d145.116101",
            coords: [-38.353257, 144.908488],
            spotID: 13856,
            pts:0
        },
        olivHill = 
        {
            name:" Olivers Hill",
            maxWindKm: 35,
            sheltFrom: ['ESE','SE'],
            goodWind: ['S','ESE','SE','WSW', 'SW'],
            tideException: ['high'],
            chnceFish: 3,
            goodFish: 1,
            species: ['Australian Salmon', 'Snapper', 'Garfish', 'Squid'],
            matchedSpecies: [],
            tips: ['Find any spot which has sandy bottom with grass beds which can you can cast into 2-7m. ', 'Fishing during the day you should be able to spot sand holes quite easily. If youre fishing at night you can afford to fish shallower as they will move into less than a foot of water under darkness.'],
            isSheltered: '<img id="outputIcon" src="img/cross.png">',
            distanceFrom: 1,
            toilets: '<img id="outputIcon" src="img/cross.png">',
            image: '<img id="spotImg" src="img/ol.jpg">',
            desc: "Olivers Hill is a locality located in the City of Frankston, Victoria in Australia. It is the first major rise in terrain along the eastern coastline of Port Phillip, between Melbourne and the Mornington Peninsula. It was named after local Frankston fisherman, James Oliver, who built the first cottage atop the hill in the mid-19th century, from where he kept watch for fish in the waters below.",
            takeMe:"https://www.google.com.au/maps/place/38%C2%B009'16.4%22S+145%C2%B006'23.5%22E/@-38.1542538,145.1089457,323m/data=!3m1!1e3!4m5!3m4!1s0x0:0x0!8m2!3d-38.154557!4d145.106539",
            coords: [-38.154577, 145.106493],
            spotID: 13856,
            pts:1
        },
        frnkPier = 
        {
            name:" Frankston Pier",
            maxWindKm: 35,
            sheltFrom: ['E'],
            goodWind: ['E','ESE','NE','NNE', 'N'],
            tideException: ['none'],
            chnceFish: 2,
            goodFish: 0,
            species: ['Australian Salmon', 'Snapper', 'Garfish', 'Squid'],
            matchedSpecies: [],
            tips: ['High tide during the early morning or late evening is primetime for a few Garfish', 'Windy days can be a make Frankston a hotspot for salmon with the occasional snapper.'],
            isSheltered: '<img id="outputIcon" src="img/cross.png">',
            distanceFrom: 1,
            toilets: '<img id="outputIcon" src="img/cross.png">',
            image: '<img id="spotImg" src="img/frnk.jpg">',
            desc: "The Frankston Brick Company used the pier during the 1880's for shipping bricks to Melbourne and receiving firewood for their brick kilns on the foreshore.<br/><br/>"+
                "Around this time a permanent lamp was built at the end of the pier and a “Lamp Lighter” was employed to keep the light burning at night during fine and foul weather.<br>"+
                "According to local residents one of the most famous visitors to use the pier was Lord Brassey, later becoming the Governor of Victoria from 1895 – 1900, when he tied his yacht “Sunbeam” up to the pier during his around the world journey in 1876-77.",
            takeMe: "https://www.google.com.au/maps/place/38%C2%B008'47.7%22S+145%C2%B006'58.0%22E/@-38.1460522,145.1136302,428m/data=!3m1!1e3!4m5!3m4!1s0x0:0x0!8m2!3d-38.146594!4d145.116101",
            coords: [-38.146825, 145.116722],
            spotID: 13856,
            pts:1
        },
        patRiver = 
        {
            name:" Patterson River",
            maxWindKm: 35,
            goodWind: ['W'],
            sheltFrom: ['SW'],//Change to 'All' ?
            tideException: ['none'],
            chnceFish: 3,
            goodFish: 6,
            species: ['Bream','Flathead','Mullet','Mulloway','Australian Salmon'],
            matchedSpecies: [],
            tips: ['Walking the bank near the boat ramp is effective when lure fishing.', 'Work the edge where it drops away to deeper water'],
            isSheltered: '<img id="outputIcon" src="img/cross.png">',
            distanceFrom: 1,
            toilets: '<img id="outputIcon" src="img/cross.png">',
            image: '<img id="spotImg" src="img/pr.jpg">',
            desc: "Patterson River is a unique man made waterway, created in 1876 to provide drainage from the Dandenong Valley catchment. Since then is has become one of the most popular boating and fishing gateways to Port Phillip. The thriving canal system of the Patterson Lakes residential area and the wet and dry storage at the marina contribute to making this an extremely busy waterway.",
            takeMe: "https://www.google.com.au/maps/place/38%C2%B004'16.4%22S+145%C2%B007'36.9%22E/@-38.071229,145.125622,509m/data=!3m2!1e3!4b1!4m5!3m4!1s0x0:0x0!8m2!3d-38.071229!4d145.126913",
            coords: [-38.071051, 145.127196],
            spotID: 13856,
            pts:1
        },
        mordialloc = 
        {
            name:" Mordialloc Pier",
            maxWindKm: 20,
            goodWind: ['SW','WSW','W'],
            sheltFrom: ['NE','ENE'],
            tideException: ['none'],
            chnceFish: 6,
            goodFish: 8,
            species: ["Snapper", "Australian Salmon", "King George Whiting", "Fladhead", "Squid"],
            matchedSpecies: [],
            tips: ['The right hand side of the pier near the "bus stop" is good for squid & whiting', 'Aim your cast 20-40m out to the edge of the reef which is visible from the pier.'],
            isSheltered: '<img id="outputIcon" src="img/cross.png">',
            distanceFrom: 1,
            toilets: '<img id="outputIcon" src="img/cross.png">',
            image: '<img id="spotImg" src="img/mp.jpg">',
            desc: "Situated on Beach Road in Mordialloc this long pier provides a range of fishing options for different species. Mordialloc Creek which runs into the bay alongside this pier offers additional fishing opportunities.",
            takeMe: "https://www.google.com.au/maps/place/38%C2%B000'35.2%22S+145%C2%B005'07.3%22E/@-38.00977,145.0840693,508m/data=!3m2!1e3!4b1!4m5!3m4!1s0x0:0x0!8m2!3d-38.00977!4d145.085357",
            coords: [-38.009770, 145.085357],
            spotID: 13856,
            pts:1   
        },
        beaumaris =
        {
            name:" Beaumaris Pier",
            maxWindKm: 20,
            goodWind: ['W', 'NW', 'NNW'],
            sheltFrom: ['NW','W'],
            tideException: ['none'],
            chnceFish: 5,
            goodFish: 6,
            species: ['Squid','Australian Salmon', 'Garfish', 'Snapper', "King George Whiting"],
            matchedSpecies: [],
            tips: ['Aim for a tide change around sunset or sunrise','Snapper: Head to the end of the pier cast directly out during a south-westerly weather event.','Care for the rig-eating reef around the jetty.'],
            isSheltered: '<img id="outputIcon" src="img/cross.png">',
            distanceFrom: 1,
            toilets: '<img id="outputIcon" src="img/cross.png">',
            image: '<img id="spotImg" src="img/bm.jpg">',
            desc: " Beaumaris Yacht Squadron Jetty is located on the Eastern Shore of Port Phillip Bay and nestles into the cliff face approximately half way between Ricketts Point and Mentone Beach. The jetty is well hidden from the Beach road and offers year round access to a good variety of species.",
            takeMe: "https://www.google.com.au/maps/place/37%C2%B059'24.9%22S+145%C2%B002'38.8%22E/@-37.990242,145.0435738,216m/data=!3m2!1e3!4b1!4m5!3m4!1s0x0:0x0!8m2!3d-37.990242!4d145.044121",
            coords: [-37.990242, 145.044121],
            spotID: 13856,
            pts:1   
        },
        blackrock = 
        {
            name:" Black Rock Pier",
            maxWindKm: 20,
            goodWind: ['E','SE','SSE','ESE'],
            sheltFrom: ['E','S','SE'],
            tideException: ['none'],
            chnceFish: 7,
            goodFish: 6,
            species: ["Snapper", "King George Whiting", "Squid"],
            matchedSpecies: [],
            tips: ['Can be pretty shallow off the pier towards the reef, fishing from the carpark with surf rods can be a better option but watch out for the rocks.'],
            isSheltered: '<img id="outputIcon" src="img/cross.png">',
            distanceFrom: 1,
            toilets: '<img id="outputIcon" src="img/cross.png">',
            image: '<img id="spotImg" src="img/br.jpg">',
            desc: "The sunken Cerberus and Red Bluff cliffs are all in the vicinity of Black Rock Pier. The Pier is just north of Black Rock. Turn left off Beach Road though a small car park and down a slope to another car parking area and boat ramp. This area is popularly called Half moon Bay.",
            takeMe: "https://www.google.com.au/maps/place/37%C2%B058'09.9%22S+145%C2%B000'36.1%22E/@-37.9686399,145.0093912,309m/data=!3m1!1e3!4m5!3m4!1s0x0:0x0!8m2!3d-37.969408!4d145.010037",
            coords: [-37.969408, 145.010037],
            spotID: 13856,
            pts:1   
        },
        sandringham = 
        {
            name:" Sandringham Breakwall",
            maxWindKm: 20,
            goodWind: ['ESE','E', 'SE'],
            sheltFrom: ['ESE','E', 'SE'],
            tideException: ['none'],
            chnceFish: 4,
            goodFish: 6,
            species: ["Snapper", "Flathead","Garfish","King George Whiting","Bream"],
            matchedSpecies: [],
            tips: ['If targeting Snapper it is best to bring your surf rod and rigs – this will give you the best opportunity to cast out further into the strike zone.','It is equally as important to bring along a gaff or long net to help land the fish as they approach the breakwall', ' If targeting other species it is always worthwhile casting soft plastics in and around the boats and pylons on the inside of the breakwall.'],
            isSheltered: '<img id="outputIcon" src="img/cross.png">',
            distanceFrom: 1,
            toilets: '<img id="outputIcon" src="img/cross.png">',
            image: '<img id="spotImg" src="img/sb.jpg">',
            desc: "The area surrounding the Sandringham breakwall is made up of a network of reefs situated in-between deep waters that can produce early season Snapper and year round Bream.",
            takeMe: "https://www.google.com.au/maps/place/37%C2%B056'47.6%22S+144%C2%B059'47.3%22E/@-37.946565,144.9959188,216m/data=!3m2!1e3!4b1!4m5!3m4!1s0x0:0x0!8m2!3d-37.946565!4d144.996466",
            coords: [-37.946565, 144.996466],
            spotID: 13856,
            pts:1   
        },
        brighton =
        {
            name:" Brighton Pier",
            maxWindKm: 20,
            goodWind: ['ESE','E', 'SE'],
            sheltFrom: ['ESE','E', 'SE'],
            tideException: ['none'],
            chnceFish: 6,
            goodFish: 8,
            species: ["Snapper", "Squid", "Flathead", "Garfish", "King George Whiting", "Gummy Shark"],
            matchedSpecies: [],
            tips: ["Snapper: bring along their surf rod and fish during or directly after a big westerly.", "Bring a long net or gaff to help you land your catch.", "King George Whiting should be targeted near and around the waters located to the sea baths side of the pier."],
            isSheltered: '<img id="outputIcon" src="img/cross.png">',
            distanceFrom: 1,
            toilets: '<img id="outputIcon" src="img/cross.png">',
            image: '<img id="spotImg" src="img/brightonpier.jpg">',
            desc: "Brighton Breakwater is a year round land-based site that offers the angler a great variety of species. The platform begins as a pier, extending out from the beach before intersecting with the rock wall.",
            takeMe: "https://www.google.com.au/maps/place/37%C2%B054'36.5%22S+144%C2%B059'08.3%22E/@-37.9065943,144.9801789,310m/data=!3m1!1e3!4m5!3m4!1s0x0:0x0!8m2!3d-37.910136!4d144.985645",
            coords: [-37.910136, 144.985645],
            spotID: 13856,
            pts:1   
        },
//        name = 
//        {
//            name:" ",
//            maxWindKm: ,
//            goodWind: [''],
//            sheltFrom: [''],
//            tideException: [''],
//            chnceFish: ,
//            goodFish: ,
//            species: [],
//            matchedSpecies: [],
//            tips: [],
//            isSheltered: '<img id="outputIcon" src="img/cross.png">',
//            distanceFrom: 1,
//            toilets: '<img id="outputIcon" src="img/cross.png">',
//            image: '<img id="spotImg" src="img/brightonpier.jpg">',
//            desc: "",
//            takeMe: "https://www.google.com.au/maps/place/38%C2%B004'16.4%22S+145%C2%B007'36.9%22E/@-38.071229,145.125622,509m/data=!3m2!1e3!4b1!4m5!3m4!1s0x0:0x0!8m2!3d-38.071229!4d145.126913",
//            coords: [],
//            spotID: ,
//            pts:1   
//        },
        jamJerrup = 
        {
            name:" Stockyard Point",
            maxWindKm: 25,
            goodWind: ['SE', 'ESE', 'NE'],
            sheltFrom: ['E', 'ESE'],
            tideException: ['low'],
            chnceFish: 6,
            goodFish: 8,
            species: ['Gummy Shark', 'Snapper', 'Mullet', 'Mulloway', 'Flathead', 'Australian Salmon'],
            matchedSpecies: [],
            tips: ['Low Tide spot only unless you want to fish from just outside the carpark','Stick to walking on the lighter shaded sand as the dark sand is soft and ending up in knee deep sand/mud is possible',' If you are planning to fish at night, full moon periods are best.', 'Cast no more that 30 - 40 meters are required to get your baits into the prime fishing area.', 'Travel light!!!'],
            isSheltered: '<img id="outputIcon" src="img/cross.png">',
            distanceFrom: 1,
            toilets: '<img id="outputIcon" src="img/cross.png">',
            image: '<img id="spotImg" src="img/sp.jpg">',
            desc: "Stockyard Point is a shallow beach that drains to the edge of a deep channel on low tide. To get there, drive down the South Gippsland Hwy then onto Bass Highway. Turn off at Bay Rd (Jam Jerrup Rd) until you reach foreshore Rd. Turn left here. Parking is available at end the of foreshore Rd. There is a 15 - 20 min walk down the walking track and then the foreshore to the left will see you reach 'Stockyard Point' Stick to walking on the lighter shaded sand as the dark sand is soft and ending up in knee deep sand/mud is possible",
            takeMe: "https://www.google.com.au/maps/place/38%C2%B020'14.5%22S+145%C2%B030'55.5%22E/@-38.337356,145.5138519,609m/data=!3m2!1e3!4b1!4m5!3m4!1s0x0:0x0!8m2!3d-38.337356!4d145.515404",
            coords: [-38.337356, 145.515404],
            spotID: 12383,
            pts:1   
        },
        stoneyPoint = 
        {
            name:" Stoney Point",
            maxWindKm: 20,
            goodWind: ['W', 'SW', 'SSW'],
            sheltFrom: ['NW','WNW','W', 'WSW', 'SSW', 'SW'],
            tideException: ['none'],
            chnceFish: 4,
            goodFish: 7,
            species: ["Snapper", "Gummy Shark", "Squid", "King George Whiting", "Leatherjacket"],
            matchedSpecies: [],
            tips: ['Try at the end of the pier on the landing there for squid', 'The pier provides food and habitat for fish of all sizes so casting away from the pier is not always required.', 'Fish only the tide change as the tide can be very strong here.'],
            isSheltered: '<img id="outputIcon" src="img/cross.png">',
            distanceFrom: 1,
            toilets: '<img id="outputIcon" src="img/cross.png">',
            image: '<img id="spotImg" src="img/cp.jpg">',
            desc: "This pier is located at Stony Point on the western side of Western Port. It acts as a port for various vessels including passenger ferries to French Island and Phillip Island. ",
            takeMe: "https://www.google.com.au/maps/place/38%C2%B022'23.2%22S+145%C2%B013'24.1%22E/@-38.373113,145.2227042,18z/data=!3m1!4b1!4m5!3m4!1s0x0:0x0!8m2!3d-38.373113!4d145.223374",
            coords: [-38.373113, 145.223374],
            spotID: 13838,
            pts:1   
        },
        langLang = 
        {
            name:" Lang Lang",
            maxWindKm: 20,
            goodWind: ['E','ENE','ESE'],
            sheltFrom: ['SE','ESE','NE', 'ENE'],
            tideException: ['high'],
            chnceFish: 3,
            goodFish: 7,
            species: ['Gummy Shark', 'Snapper', 'Mullet', 'Mulloway', 'Flathead', 'Australian Salmon'],
            matchedSpecies: [],
            tips: ['Only fishable at High tide, so try to aim for the highest tide possible. 1.8m is ideal.'],
            isSheltered: '<img id="outputIcon" src="img/cross.png">',
            distanceFrom: 1,
            toilets: '<img id="outputIcon" src="img/tick.png">',
            image: '<img id="spotImg" src="img/ll.jpg">',
            desc: "Lang Lang is a high tide fishing spot - your other option is to head down bay road to Jam Jerrup and wander down to Stockyard point - it's a fairly long walk but many good fish have come from that area. <br/><br/>A nice place where you can fish from the carpark in your car!",
            takeMe: "https://www.google.com.au/maps/place/38%C2%B018'22.4%22S+145%C2%B031'16.5%22E/@-38.306222,145.5201517,18z/data=!3m1!4b1!4m5!3m4!1s0x0:0x0!8m2!3d-38.306222!4d145.521246",
            coords: [-38.306222, 145.521246],
            spotID: 12383,
            pts:1   
        },
        grantville = 
        {
            name:" Grantville Pier",
            maxWindKm: 20,
            goodWind: ['SE', 'ESE', 'SW'],
            sheltFrom: ['ENE','NE','E'],
            tideException: ['high'],
            chnceFish: 4,
            goodFish: 7,
            species: ['Gummy Shark', 'Snapper', 'Mullet', 'Mulloway', 'Flathead', 'Australian Salmon'],
            matchedSpecies: [],
            tips: ['Only fishable at High tide, so try to aim for the highest tide possible. 1.8m is ideal.'],
            isSheltered: '<img id="outputIcon" src="img/cross.png">',
            distanceFrom: 1,
            toilets: '<img id="outputIcon" src="img/tick.png">',
            image: '<img id="spotImg" src="img/gp.jpg">',
            desc: "Grantville was established as a supply port situated on the east coast of Western Port. The jetty would bring in supplies for the nearby area in the Gippsland region. Sawmills were soon built and Grantville took a turn to become a town centered on timber. Short tramways were constructed between the sawmills and the jetty. The timber was then shipped to Melbourne",
            takeMe: "https://www.google.com.au/maps/place/38%C2%B024'24.4%22S+145%C2%B031'34.4%22E/@-38.406789,145.5254926,284m/data=!3m2!1e3!4b1!4m5!3m4!1s0x0:0x0!8m2!3d-38.406789!4d145.526216",
            coords: [-38.406789, 145.526216],
            spotID: 12383,
            pts:1   
        },
        tenbyPoint = 
        {
            name:" Tenby Point",
            maxWindKm: 20,
            goodWind: ['SE', 'ESE', 'SW', 'S'],
            sheltFrom: ['SE', 'ESE', 'SW', 'S', 'WSW','ESE'],
            tideException: ['high'],
            chnceFish: 6,
            goodFish: 6,
            species: ['Gummy Shark', 'Snapper', 'Mullet', 'Mulloway', 'Flathead', 'Australian Salmon'],
            matchedSpecies: [],
            tips: ['Only fishable at High tide, so try to aim for the highest tide possible. 1.8m is ideal.', 'Stick to walking on the lighter shaded sand as the dark sand is soft and ending up in knee deep sand/mud is possible', 'Good place for an Elephant Fish in season.'],
            isSheltered: '<img id="outputIcon" src="img/cross.png">',
            distanceFrom: 1,
            toilets: '<img id="outputIcon" src="img/cross.png">',
            image: '<img id="spotImg" src="img/tb.jpg">',
            desc: "Head down Bayview Ave all the way to the end, enter the beach and head to the right until you see the pylons from the old pier.",
            takeMe: "https://www.google.com.au/maps/place/38%C2%B024'26.2%22S+145%C2%B028'51.9%22E/@-38.407275,145.4803622,281m/data=!3m2!1e3!4b1!4m5!3m4!1s0x0:0x0!8m2!3d-38.407275!4d145.481078",
            coords: [-38.407275, 145.481078],
            spotID: 12383,
            pts:1   
        },
        corinella = 
        {
            name:" Corinella Pier",
            maxWindKm: 20,
            goodWind: ['S','SSE','SW','SSW'],
            sheltFrom: ['S','ESE', 'SE', 'SW' , 'SSW'],
            tideException: ['none'],
            chnceFish: 5,
            goodFish: 8,
            species: ['Gummy Shark', 'Snapper', 'Mullet', 'Mulloway', 'Squid', 'Australian Salmon','Trevally'],
            matchedSpecies: [],
            tips: ['Checkout the pier on low tide before venturing out for a good idea of the area.','Cast no more than 10m on the edge of the channel out front.'],
            isSheltered: '<img id="outputIcon" src="img/cross.png">',
            distanceFrom: 1,
            toilets: '<img id="outputIcon" src="img/cross.png">',
            image: '<img id="spotImg" src="img/co.jpg">',
            desc: "Jarrod Day profiles Corinella Pier in Western Port Bay that can provide some great land based action for anglers without a boat. Corinella is around on the far side of Western Port for Melbourne-based anglers, but it's worth the drive to access the diverse range of species available.",
            takeMe: "https://www.google.com.au/maps/place/38%C2%B024'26.2%22S+145%C2%B028'51.9%22E/@-38.4070534,145.422271,149m/data=!3m1!1e3!4m5!3m4!1s0x0:0x0!8m2!3d-38.407275!4d145.481078",
            coords: [-38.407275, 145.481078],
            spotID: 12383,
            pts:1   
        },
        tooradin = 
        {
            name:" Tooradin",
            maxWindKm: 20,
            goodWind: ['N', 'NNE', 'NNW'],
            sheltFrom: ['N','NE', 'NNE', 'NW' , 'NNW', 'E', 'W'],
            tideException: ['high'],
            chnceFish: 4,
            goodFish: 2,
            species: ['Bream', 'Mullet', 'Silver Trevally', 'Flathead'],
            matchedSpecies: [],
            tips: ['Using light tackle and some berley will improve results when fishing here.', 'A running sinker rig is suitable for most species.', 'Use a float and small long-shanked hooks for mullet.', 'Fishing is best around high tide.'],
            isSheltered: '<img id="outputIcon" src="img/cross.png">',
            distanceFrom: 1,
            toilets: '<img id="outputIcon" src="img/tick.png">',
            image: '<img id="spotImg" src="img/to.jpg">',
            desc: "The town of Tooradin is located on this inlet which is on the northern end of Western Port. You can fish from a jetty as well as many ideal spots along the banks.",
            takeMe: "https://www.google.com.au/maps/place/38%C2%B012'50.5%22S+145%C2%B022'44.7%22E/@-38.21403,145.3785268,215m/data=!3m2!1e3!4b1!4m5!3m4!1s0x0:0x0!8m2!3d-38.21403!4d145.379074",
            coords: [-38.214030, 145.379074],
            spotID: 12383,
            pts:1   
        },
        cannonsCreek = 
        {
            name:" Cannons Creek",
            maxWindKm: 20,
            goodWind: ['N', 'NNW', 'NNE'],
            sheltFrom: ['N', 'NNW', 'NNE'],
            tideException: ['high'],
            chnceFish: 8,
            goodFish: 4,
            species: ["Mullet", "Flathead", "King George Whiting", "Mulloway", "Bream", "Silver Trevally"],
            matchedSpecies: [],
            tips: ['Usually considered a high-tide only spot, but can produce at night at low tide.', 'Bring the bait pump and pump for bass yabbies on the beach to use for the best bait possible.'],
            isSheltered: '<img id="outputIcon" src="img/cross.png">',
            distanceFrom: 1,
            toilets: '<img id="outputIcon" src="img/cross.png">',
            image: '<img id="spotImg" src="img/cc.jpg">',
            desc: "A nice quiet spot for the family & kids to relax on a usually quiet beach whilst you sneak a line in.",
            takeMe: "https://www.google.com.au/maps/place/38%C2%B012'53.4%22S+145%C2%B018'35.6%22E/@-38.21483,145.3093468,215m/data=!3m2!1e3!4b1!4m5!3m4!1s0x0:0x0!8m2!3d-38.21483!4d145.309894",
            coords: [-38.214830, 145.309894],
            spotID: 13838,
            pts:1   
        },
        warneet = 
        {
            name:" Warneet Pier",
            maxWindKm: 20,
            goodWind: ['NNE','NE', 'N', 'NNW', 'NW'],
            sheltFrom: ['E','ESE','SE'],
            tideException: ['high'],
            chnceFish: 6,
            goodFish: 6,
            species: ["Squid", "Flathead", "King George Whiting", "Silver Trevally"],
            matchedSpecies: [],
            tips: ['Tide can run super fast here, aim for the tide changes', 'Typically too low to fish at low tide'],
            isSheltered: '<img id="outputIcon" src="img/cross.png">',
            distanceFrom: 1,
            toilets: '<img id="outputIcon" src="img/cross.png">',
            image: '<img id="spotImg" src="img/wp.jpg">',
            desc: "The fast running tide can usually be a bit of a buzz kill here, aim for the tide changes. Theres a tackleshop & boatramp here too.",
            takeMe: "https://www.google.com.au/maps/place/38%C2%B013'38.0%22S+145%C2%B018'26.7%22E/@-38.2273969,145.3069874,215m/data=!3m1!1e3!4m5!3m4!1s0x0:0x0!8m2!3d-38.227208!4d145.307409",
            coords: [-38.227208, 145.307409],
            spotID: 13838,
            pts:1   
        },
        hastings = 
        {
            name:" Hastings Pier",
            maxWindKm: 20,
            goodWind: ['W','SW','WSW'],
            sheltFrom: ['WNW','NNW', 'NW', 'W', 'WSW'],
            tideException: ['none'],
            chnceFish: 4,
            goodFish: 4,
            species: ["King George Whiting", "Australian Salmon", "Silver Trevally", "Flathead"],
            matchedSpecies: [],
            tips: ['Fishing around high tide is most productive.', 'Cast into sand patches when fishing for flathead and whiting, Silver trevally can be caught around the pylons.'],
            isSheltered: '<img id="outputIcon" src="img/cross.png">',
            distanceFrom: 1,
            toilets: '<img id="outputIcon" src="img/cross.png">',
            image: '<img id="spotImg" src="img/hs.jpg">',
            desc: "This jetty is located on Skinner Street in Hastings and provides fishing for popular species all year round.",
            takeMe: "https://www.google.com.au/maps/place/38%C2%B018'30.7%22S+145%C2%B011'51.1%22E/@-38.308522,145.1969868,215m/data=!3m2!1e3!4b1!4m5!3m4!1s0x0:0x0!8m2!3d-38.308522!4d145.197534",
            coords: [-38.308522, 145.197534],
            spotID: 13838,
            pts:1   
        },
        flinders = 
        {
            name:" Flinders Pier",
            maxWindKm: 20,
            goodWind: [''],
            sheltFrom: ['NNE','NE', 'N', 'NNW', 'NW'],
            tideException: ['S','SW','SSW'],
            chnceFish: 6,
            goodFish: 5,
            species: ["Squid", "King George Whiting", "Mullet", "Australian Salmon", "Silver Trevally", "Wrasse", "Leatherjacket"],
            matchedSpecies: [],
            tips: ['The run-in tide is most productive for all species.', 'Cast into sand patches when fishing for whiting.', 'ishing around the pylons will produce wrasse and leatherjackets.', 'Squid: Baited Jigs are most effective here & can help avoid losing alot of expensive squid jigs to the weedbeds.'],
            isSheltered: '<img id="outputIcon" src="img/cross.png">',
            distanceFrom: 1,
            toilets: '<img id="outputIcon" src="img/cross.png">',
            image: '<img id="spotImg" src="img/fl.jpg">',
            desc: "This jetty is located at the end of Bass Street in Flinders on the Mornington Peninsula. This jetty has a reputation for producing excellent squid catches with some very large specimens caught in spring",
            takeMe: "https://www.google.com.au/maps/place/38%C2%B028'31.5%22S+145%C2%B001'29.9%22E/@-38.475425,145.0241365,327m/data=!3m2!1e3!4b1!4m5!3m4!1s0x0:0x0!8m2!3d-38.475425!4d145.02497",
            coords: [-38.475425, 145.024970],
            spotID: 13838,
            pts:1   
        },
        merricksSomers = 
        {
            name:" Merricks Beach",
            maxWindKm: 20,
            goodWind: ['NNE','NE', 'N', 'NNW', 'NW'],
            sheltFrom: ['N', 'NE', 'NW'],
            tideException: ['high'],
            chnceFish: 6,
            goodFish: 7,
            species: ["King George Whiting", "Gummy Shark", "Squid", "Mullet", "Flathead", "Australian Salmon"],
            matchedSpecies: [],
            tips: ['The beach fishes best at high tide, particularly if this occurs early in the morning.', 'Night time is recommended if you wish to catch a gummy shark.'],
            isSheltered: '<img id="outputIcon" src="img/cross.png">',
            distanceFrom: 1,
            toilets: '<img id="outputIcon" src="img/cross.png">',
            image: '<img id="spotImg" src="img/me.jpg">',
            desc: "This beach is located at the end of Merricks Beach Road in Merricks. The long sandy stretch provides roomy for plenty of anglers.",
            takeMe: "https://www.google.com.au/maps/place/38%C2%B023'37.3%22S+145%C2%B009'26.6%22E/@-38.393698,145.1568318,215m/data=!3m2!1e3!4b1!4m5!3m4!1s0x0:0x0!8m2!3d-38.393698!4d145.157379",
            coords: [-38.393698, 145.157379],
            spotID: 13838,
            pts:1   
        },
    ];